CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 python -u -W ignore run_avcap.py \
    --dataset audiocaps \
    --print_freq 10 \
    --lr 1e-4 --max_epoch 30 --batch-size 8 \
    --num_frames 4 \
    --target_length 1024 --noise True \
    --av_pretrain_path ../mmcap_git/pretrained_weights/cav-mae-scale++.pth \
    --text_pretrain_path ../mmcap_git/pretrained_weights/model_git_base.pt \
    --save_path avcap_base_lr1e-4_ft_numframe4 \
    --train_base_path 'data/train' \
    --test_base_path 'data/test' \
    --freeze_text \
    --modality_specific_depth 11 \
    --no_wandb